branch: master # не обязательно
venv_requirements: requirements.txt # не обязательно указывать
venv_folder: venv # не обязательно


hosts:
    - sebuntu@192.168.15.149:22
    - sebuntu@192.168.13.232:22
work_service: rabbitmq-server
path: ~/work/fabtest/
repository: https://github.com/faoxis/gittest.git
path_key: ~/.ssh/id_rsa
migrate_command: echo 'something' >> superultimatemigrate.txt

